### ISSUE TITLE
Game stalls

### ISSUE THREAD

**Issue by txomon** [simonswain/deepspace#1]
Hi!,

I have been testing using http://simonswain.com/deepspace/make_empires and the simulation stalls, mainly because there are ships that don't evolve further. This is, they get into a system, and they kill all the ships in there, no matter how many.

I would propose that ships just lasted 2 or 3 minutes. Also, I don't understand why they are capable of destroy that many ships when they are alone in the system.

**Comment by SeverinDK** [comment]
If the ships only lived for 2-3 minutes, then it would kinda ruin the point of the simulation. The idea of these simulations is to just sit back and enjoy how a few simple rules turn into something much bigger. If we just tell them to die after 2-3 mins, then it's not much of a simulation anymore in my opinion.

Have a look at this video if you haven't seen it already : https://www.youtube.com/watch?v=0HJPilemNns - He explains a lot about what's going on in the simulations in that video.

**Comment by txomon** [comment]
Sure! I have come from there! If you want to get realistic, we should say that ships have limited time span, they get broken, and that they should go back to a planet to take fuel.

In any case, my idea was to avoid a situation where there still exist ships on their own. They are stalled in a system, killing everything in there (I still can't explain how they don't get killed) forever, ending up with two winners, who have each one 1 enemy ship in their system shooting at them. Will post an screenshot later if I can...

**Comment by SeverinDK** [comment]
I haven't really looked into the code much yet, so I'm not really sure what kind of stats those ships have. But something as simple as fuel and durability (Affected by both time and battle damage) would do a lot for the simulation, if they haven't been added already. Maybe also add crews to the ships and have them age and die, so each ship would have to return home to resupply it's resources.

Another thing I noticed when I first saw the simulation is that the ships don't really talk to each other when they attack another system. Seems like it's pretty random where they go. It would be cool if a system knew how many ships it has sent to other systems. This could be improved even further if a ships returns a small messenger back home when it gets to a new system, with information about this new system. That way new ships could decide where it would be best to go. If a newly discovered system is empty but already has 3 of your ships, then there wouldnt be any point for a new ship to travel there, compared to a system that has a battle going on. 

Maybe also add a feature for a planet to "eat" a ship for it's resources. If there isn't any reason to travel anywhere, then why not use the resources the ship is made of on something else?

**Comment by txomon** [comment]
Well, my idea was just to avoid stalled ships being in a system. Maybe limiting their life to time is not good, but yes that if they are alone against 6, they actually get killed, because I see ships that don't attack the enemy, although the enemy attacks them...

I don't know if you can see it, but there is a green one, whose civilization dissappeared in minute 1, and it's been 30 minutes there killing all the ships in that system alone...

![screenshot from 2015-01-07 20 17 27](https://cloud.githubusercontent.com/assets/228250/5651736/49144d24-96aa-11e4-9376-7e52188ad22a.png)

**Comment by txomon** [comment]
This is another extreme case, started with 15 ships yellow, 3 ships blue, win blue without any damage...

![screenshot from 2015-01-07 20 19 34](https://cloud.githubusercontent.com/assets/228250/5651764/974940ee-96aa-11e4-9357-2a2ee45bc238.png)

**Comment by txomon** [comment]
This is the state of an empire, without changes, in 24 hours running. Notice that there is one spaceship in each system that doesn't belong, and that destroys the rest.

![screenshot from 2015-01-08 09 26 12](https://cloud.githubusercontent.com/assets/228250/5659797/8e0cd36a-9718-11e4-92a6-3ae180d35f30.png)

**Comment by txomon** [comment]
I have improved stabilization changing this line:
https://github.com/simonswain/deepspace/blob/master/server/public/js/models/ship.js#L247

by 

```
    if(enemies){
```

**Comment by simonswain** [comment]
Hi -- sorry late reply.

There are a few bugs in there I've noticed. I've seen both the ones you mentioned but haven't dug in to look at them

You're on the right track with the `if(enemies)` line above.  I think I can what's wrong with it now -- It includes itself in the friends count (should exclude), and it should check the intent of the other friendlies. If there are more fight-intent friendlies than enemies, then it's free to jump or colonize, else it should join the fight. A set of same colored ships always want to have more in the fight than the enemy. Basically that code was good enough for the presentation, but doesn't hold up for longer runs.

**Comment by simonswain** [comment]
The logic for where ships jump is in `App.Models.Ship.prepJump()`

It prioritizes where to jump something like:
- choose an empty (uncolonized) system
- choose one we have started colonizing already
- choose one that is mixed
- choose one totally owned by the enemy

This is the cause of another bug, as a system on the edge, with friendly systems all around it won't send any ships out of system (the never jump to the friendly neighbour systems). To get around this they need a bit more enhanced jump targeting, so they have a final destination, and select waypoints to pass through, or something along those lines.

**Comment by simonswain** [comment]
Self destruction ships would be fairly easy to do. Add a `ttl` attr to the ship model, and give it an `n + random` value. Decrement it each tick. When it hits zero, to a self.boom() to get rid of the ship. I think that would work. The destroy all the other ships thing is a bug for sure. I think that's an issue with the ships's intent as mentioned above.

**Comment by simonswain** [comment]
Thanks guys for taking time to play with Deep Space and your great feedback.

**Comment by txomon** [comment]
About the destruction, was really a bad way to handle the other behaviour, =)

I will try to have a look once more (although I have no idea of js) and try to play with the things you explained!

**Comment by simonswain** [comment]
Thanks. When I get a minute I'll have a look at those issues I mentioned also.
